<?php

// this function is used for html scraping. 
// requires: $url is a link containing html

function scrapper($url) {
    $curl = curl_init($url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    $html = curl_exec($curl);
    curl_close($curl);

    //Creating a DOMDocument
    $doc = new DOMDocument();

    //Avoid the presentation of warnings due to ill-created HTML results
    libxml_use_internal_errors(true);
    $doc->loadHTML($html);
    libxml_clear_errors();

    //An alternative way to apply XPath to a result, in this case filtering a DOM tree
    $xpath = new DOMXpath($doc);
    return $xpath;
}

// this is a general function used to create an array from a DOMXPath class
// requires $xpath is object of class DOMXPath generated by scrapper() 

function createArray($xpath) {
    $list = array();
    foreach ($xpath as $temp){
        array_push($list, $temp->nodeValue); 
    }
    return $list;
}

?>